### ISSUE TITLE
硬漢法

### ISSUE THREAD

**Issue by selrahc** [William-Yeh/ansible-git-deploy-demo#1]
Hi William,

威廉您好，希望不會打擾到您，我是您的讀者及 Docker Workshop 的學生（2015 年 3 月），日前拜讀了您的「利用 Ansible 部署 GitHub 專案的設定細節」一文，在最後的「換你動手試試看！」的地方，我試著想要用「硬漢法 ><」去部署 Vagrant 啟動的虛擬機，試了好久最後才成功。我指令是這樣下的：

ansible-playbook -i inventory.ini --private-key=.vagrant/machines/default/virtualbox/private_key -u vagrant playbook.yml

另外我的 host OS 是 Windows 7，我裝了 Cygwin 去下上面的指令，卡關了很多次我才找到要先去把 private_key 的 permission 改掉：

chmod 700 .vagrant/machines/default/virtualbox/private_key

因為您那篇大作裡面沒有提到 local 虛擬機的 ansible-playbook 指令，所以我才想說回文在您這邊，希望沒有不恰當，也希望您不會介意。

我發現威廉您後來 Ansible 與 Docker 的整合使用是在 Docker 裡面去跑 Ansible（cf. William-Yeh/docker-ansible），請教您為什麼不是利用 Ansible 去部署 Docker container 就好，反而是在 Docker container 裡面跑 Ansible 呢？

Cheers,

Charles

**Comment by William-Yeh** [comment]
您好：

關於第一個問題，目前 Ansible 的 "control machine" 仍然是以 Mac OS X 及 Linux 為主。

引述兩則 Ansible 官方說法：

(1) http://docs.ansible.com/intro_windows.html

> Ansible will still be run from a Linux control machine, and uses the “winrm” Python module to talk to remote hosts.

(2) https://groups.google.com/forum/#!topic/ansible-project/ayJ3nd0YTIc

>  it's not guaranteed that Ansible will continue to run on a Windows host, we reserve the right to use native Linux services (even /dev/random) so you will need to run Ansible from a Linux/Unix/OSX control host.

Jeff Geerling 在他的文章 [Running Ansible within Windows](https://servercheck.in/blog/running-ansible-within-windows) 及電子書 [_Ansible for DevOps_](https://leanpub.com/ansible-for-devops) 有介紹一些變通方法，不過仍不完美，要有不時會踩到地雷的心理準備。

##

**Comment by William-Yeh** [comment]
關於第二個問題，要先理解一點：「Ansible + Docker」有很多種角度及用法。

你所提的用法，是**把 Ansible 當成是一種 application deployment 工具**，而 Docker 只是其中一種可以被 deploy 上去的 application。

而我的 [williamyeh/ansible](https://github.com/William-Yeh/docker-ansible)，用途是：
1. **把 Docker 當成輕量級的 VM**：啟用「Docker + Ansible」比啟動「VM + Ansible」快、省資源、省前置作業，尤其在有需要模擬各家各派 Linux VM 時。<br/><br/>譬如說，Travis CI 和 CircleCI 的 worker VM 只有提供 Ubuntu 12.04，可是萬一我還需要在 Ubuntu 14.04、Debian 7 & 8、CentOS 6 & 7 去測我的一堆 Ansible playbooks，該怎麼辦？解答就是：用 Docker 的 `ubuntu:14.04`、`debian:wheezy`、`debian:jessie`、`centos:centos6`、`centos:centos7` 這些 base image 來模擬那一堆 VM。
2. **快速把既有的 Ansible playbook 部署到 Docker 上**，避免還要重寫一份 `Dockerfile`。不過，我不建議這種用法。

**Comment by selrahc** [comment]
Hi William,

謝謝您特別地回文解惑！真的很謝謝。^O^

Cheers,

Charles
